extract = 'total_dyn_inst: (\d+)'
benchmarks = '../bril/benchmarks/*.bril'
timeout = 10

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.myopt]
pipeline = [
    "bril2json",
    "python3 cli.py",
    "brili -p {args}",
]
